---
title: "General Notes"
output: html_document
---

Paired vs single end
Paired End: Paired-end sequencing involves sequencing DNA from both ends of a fragment. Choose this option if your sequence files are paired and have been demultiplexed. For example, Illumina MiSeq Paired End fastq files consist of two files for each sample with names ending on “R1_001.fastq” and “R2_001.fastq”
Single End: Single-end sequencing involves sequencing DNA from only one end. Choose this option if your samples only got sequenced from one end or if you don’t want to use the reverse fastq file.
How does DNA replicate and how do you get DNA to protein and how do modifications occur to turn on and off genes occur? Signals from the environment or from other cells activate proteins called transcription factors. These proteins bind to regulatory regions of a gene and increase or decrease the level of transcription. 
single nucleotide polymorphism 
DNA Sequencing
When building a pipeline, you build it for the questions you want to answer. If you want to look at variant discovery, don’t do RNA seq because looking for mutations in the RNA is difficult. 
Whole genome shotgun sequencing, get all the DNA you can from the sample, fragment it, and sequence the fragments. It will pick up all the genes so we know what the microbe is capable of. You will also probably get host DNA in your microbe sample. Larger genomespace because you your microbe could potentially be any microbe that’s in the database. You may find that some genetic elements like the virulence factor of salomnilla came in via bacteriophage and can show up in other microbes and if you get a match, you may think you have pathogenic salmonilla. 
Targeted Sequencing
Can get around some problems of DNA sequencing but also has problems. You pick a gene that is common to all your species of interest that should have some conserved regions that you can prime to and some variable regions that you can use to identify the different species, but the best you can do is infer function of the gene or region, you’re not sequencing other genes so the best you can do is: E.coli tends to behave a certain way, I’m seeing E. Coli so I infer these will behave the same way. 
RNA sequencing/ Metatranscriptomics
Transcripts can be tied back to origin by sequence. If a gene isn’t being expressed, you wont see it in the transcriptome. Need to remove rRNA. You want the mRNA not the rRNA. You will get quantative gene expression, so you know what they are doing because you know what genes are activated.
What to look for in a targeted sequencing gene?
Must be sequenceable, if it has high GC content, you don’t want to use it. You want highly conserved regions surrounded by highly variable regions. It has to be present in your target species, obviously. Ideally you want it absent in non-targeted species. 16S is in microbes, but not in archea and eukaryotes. 
When sequencing the 16S gene, we are sequencing the part of the ribosome that is shown below, that is involved in the translation of mRNA to amino acids. 
 
16S Sequencing challenges
Illumina makes 2% base call errors. Nanopore makes more errors but makes long reads, long enough to read the entire 16S region. Errors are a problem because if you make an error, you may be confusing the error for real diversity or a new species. Somehow, we need to deal with errors. You can Blur or Sharpen.
Blur (clustering)
I won’t worry about single nucleotide differences. You separate into Operational Taxonomic Units that contain a cluster of related microbes. If you run more samples, your clustering may change. 
OTU picking can be guided by reference sequences in your sample and you build you clusters around the reference sequences. You can also do de novo (reference free). Closed reference is when OTUs are limited to the references. Open reference is you try to use the reference species but if you don’t have a close enough match to said reference you can de novo cluster which is when you build clusters from the sample. 
OTU approach
You combine sequences that are 97% or more identical to the same species though this may only get you down to genus level. 
1.	Preprocessing (demultiplexing, etc)
2.	Pick OTUs
a.	Fast and efficient if guided by a reference set but limited to a reference set
b.	Slower if using Open References
c.	Very slow if doing de novo assembly 
3.	Extract representative sequence from each OUT (each cluster will have a consensus sequence that describes the OTU or use the consensus sequence to compare it to a reference that it looks most like.
4.	Conduct further analysis with representative sequences that can represent one or more organisms from your sample to look at diversity… etc. 
ASV (Amplicon sequence variant)

Considers frequency of the number of sequences that match a specific species. You know that you saw 2 counts of one species but you also know that error frequency would account for seeing 2 of those reads. You use the error model for the run to determine what variations we expect to see based on the error model. If our error model predicts we will see this error x% and we see that error x%, we can say that those are just artifacts of sequencing and those species don’t actually exist. We can see that statistically, what we are seeing is not a statistical artifact. 
Target gene sequencing
Throws out amplicon sequences that lack strong statistical support for not being artifacts of sequencing. Cost: potential loss of real sequence that was present at very low levels. 
1.	Preprocess reads (demultiplex, etc)
2.	Trim and filter reads to retain highest possible quality sequence
3.	Build an error model for forward and reverse reads. Error model determines the probability of seeing a change in a certain base quantity
4.	Merge forward and reverse reads into a single amplicon at an overlap region (good to use MiSeq because it has long reads)
5.	Count occurrences of each amplicon. 
6.	Use error model to determine support for rare amplicons based on the frequency. Which of those rare amplicons can be explained using sequence error. 
7.	Eliminate poorly-supported amplicons
8.	Conduct further analysis. You don’t need to use a consensus sequence like OTUs. You can actually use the sequence. 

Sharpen
DADA2 to do ASV analysis.
ASVs vs OTUs
OTUs are great if you want to compare to older samples because they are the original method and have been used for longer. 
You can build OTUs pretty compultationally easily by using the reference databases.
Databases are overrepresented for E. coli, Human samples, and food samples
ASVs don’t use any reference
One option is to build OTUs de novo which you would do if you are building an environmental microbiome sample. Problems: de novo OTU building is computationally expensive (slow, better computer doesn’t matter, can’t run in parallel). If you cluster on some samples then get more samples, you have to cluster again with the new and old samples. Compare that to ASV where if you just have ASV, this is the exact sequence of a microbe that I can support as existing in my sample and not a potential sequence error. Clustering (building OTUs) is like blurring where you group microbiota together. 
Building a reference genome de novo for one species: It is very hard and expensive. If you are going to do it. Look up hybrid assembly, use a nanopore because its easier to find. 

Type Species
The goal of this ambitious but, given the currently available technologies, assuredly tractable initiative is to sequence the genome of at least one representative of every bacterial and archaeal species whose name has been validly published in accordance with the International Code of Nomenclature of Bacteria (Bacteriological Code) [14]–[19].
Each of these approximately 11,000 bacterial and archaeal species has a designated type strain, a living culture that serves as a fixed reference point for the assignment of bacterial and archaeal names, thus often also denoted as a reference strain (see Box 1). A type strain is not the archetypal representative of a species, a common misperception. Thus, type strains play a crucial role in defining the phylogenomic and taxonomic space of Bacteria and Archaea, facilitating efforts to assign evolutionary relationships and identify new species. By definition, type strains are descendants of the original isolates used in species and subspecies descriptions, as defined by the Bacteriological Code [14], that exhibit all of the relevant phenotypic and genotypic properties cited in the original published taxonomic circumscriptions. They are made available in pure culture (except in cases such as symbionts) for subsequent taxonomic revision in accordance with the rules defined by the Bacteriological Code [14],[17]–[19]. The type strains represent the only area of the microbiological sciences in which the deposit and availability of biological material is mandatory, allowing the verification of past work and potentially extending to further aspects as time and technology become available by using the same biological material.
16S rRNA
The DNA of different bacteria can be highly variable but the 16S rRNA gene is highly conserved between bacteria. 
ANI

The average nucleotide identity (ANI) determines if two genomes belong to the same species. Average Nucleotide Identity (ANI) is a measure of nucleotide-level genomic similarity between the coding regions of two genomes
The average nucleotide identity (ANI) is a similarity index between a given pair of genomes that can be applicable to prokaryotic organisms independently of their G+C content, and a cutoff score of >95% indicates that they belong to the same species (1, 2). Despite the fact that some of the genomes published in Genome Announcements include ANI values with closely related genomes (3,–6), these data are missing in many studies. The genome sequencing studies may use different software packages for ANI determination (3,–6). The currently available software tools for ANI calculation include programs that have to be downloaded, like JSpecies (http://www.imedea.uib.es/jspecies) and Gegenees (http://www.gegenees.org/documentation.html), as well as online calculation tools, like the one at the EzGenome (http://www.ezbiocloud.net/ezgenome/ani) and the ANI calculator (http://enve-omics.ce.gatech.edu/ani/index). However, there is a lack of information indicating whether these tools provide consistent results.
In a recent study using ANI calculations and a multilocus phylogenetic analysis (MLPA), we discovered that 14 (36%) of the 39 Aeromonas genomes deposited in the GenBank genome database were taxonomically mislabeled and that ANI values can vary using different calculation tools (7). Of the different tools employed, the ANI calculator always provided higher values than the JSpecies and the EzGenome tools that provided very similar results, but the magnitude of the differences depended on the specific genomes that were compared. For instance, the ANI calculator provided results between the genomes Aeromonas hydrophila HZM (GenBank accession no. JEMQ01) and A. hydrophila ATCC 7966T (GenBank accession no. CP000462) of 89.0%, but when using JSpecies, the ANI was 86.6%. These results were <95% (the species ANI cutoff value) and therefore showed that the genome A. hydrophila HZM does not affiliate with A. hydrophila. This was also confirmed by the MLPA, because in the obtained tree, A. hydrophila HZM did not cluster with the type strain of A. hydrophila but with that of Aeromonas caviae instead. In fact, the ANI comparison between the genome of A. hydrophila HZM with that of A. caviae Ae398 (GenBank accession no. CACP01) showed results of >95% (98.4% with ANI calculator and 98.1% with JSpecies), clearly indicating that HZM belongs to the species A. caviae.

16S Pipeline
Figure S2. Bioinformatics pipeline for bacterial community analysis. The primer sequences were discarded using in-house JAVA program. Non-specific amplicons that do not encode 16S rRNA are detected by HMMER’s hmmsearch program (Eddy, 2011) with 16S rRNA profiles. All sequences were denoised by DUDE-Seq (http://data.snu.ac.kr/pub/dude-seq/) and non-redundant reads were extracted by UCLUST-clustering (Edgar, 2010). Taxonomic identification was assigned against the EzBioCloud database using USEARCH (8.1.1861_i86linux32) (Edgar, 2010) followed by more precise pairwise alignment (Myers & Miller, 1988). The chimera sequences were detected by UCHIME (Edgar et al., 2011). Only sequencing reads with lower than 97% similarity to EzBioCloud database were considered for chimera detection. Operational taxonomic units (OTUs) in the sample were investigated using open-reference method (Rideout et al., 2014) with CD-HIT (Fu et al., 2012) and UCLUST (Edgar, 2010). The alpha diversity indices and rarefaction curves were estimated by in-house code.
 
All genomes were identified taxonomically at the genus, species or subspecies levels using a combination of gene-based search and OrthoANI [10] calculations.
OAT 
https://www.ezbiocloud.net/tools/orthoani
Welcome to ChunLab's Orthologous Average Nucleotide Identity Tool (OAT),
a similarity measurement tool for genomes.
Overview
OAT uses OrthoANI to measure the overall similarity between two genome sequences. ANI and OrthoANI are comparable algorithms: they share the same species demarcation cut-off at 95~96% and large comparison studies have demonstrated both algorithms to produce near identical reciprocal similarities. Details of the OrthoANI algorithm is given in (Lee et al. 2015). OAT employs an easy-to-follow Graphical User Interface that allow researchers to calculate OrthoANI values between genomes of interest without unfamiliar Command Line Environments. Moreover, the OAT_cmd command-line software can be integrated into preexisting bioinformatics pipelines.

What is ContEst16S?
https://www.ezbiocloud.net/tools/contest16s
The result of microbial genome sequencing projects often contain unwanted information originated from contamination by either cells or DNAs from other organisms. It is nearly impossible to detect every contamination event, especially from partially sequenced genome assemblies. However, using a robust phylogenetic marker that is not easily subjected to lateral gene transfer may provide a way to detect some clear contamination cases. Here, we present a new method named ContEst16S (Contamination Estimator by 16S), in which 16S rRNA gene fragments from the query genome assemblies are screened to see if the genome assembly is contaminated or not.

