---
title: "Exploring Arlington Bikeometers Part 1 (Query the API)"
output: github_document
---

[Jump to the code]()

# Background

In 2020, Minnesota's DOT Office of Transit and Active Transportation put out a great visualization of Minneapolis' surge in bicycle and pedestrian usage soon after Minneapolis' governor Tim Walz declared a peacetime emergency on March 13, 2020 and a Stay at Home order twelve days later on March 25. Daily totals of bicycle + pedestrian counts from March 13, 2020 to May 15, 2020 were graphed against 2017-2019 daily averages.

<https://storymaps.arcgis.com/stories/70a3a57003b541ed8e911cd11103dc6a>

# Goal

Similarly explore Arlington, Virginia's bicycle ridership numbers around Virginia Governor Northram's State of Emergency Declaration (March 12, 2020) and Stay at Home order (March 30, 2020).

<https://www.governor.virginia.gov/newsroom/all-releases/2020/march/headline-853537-en.html> <https://www.governor.virginia.gov/newsroom/all-releases/2020/march/headline-855702-en.html>

# Why

Yesterday, after helping teach my friend how to ride a bike, we excitedly visited the local bike shop to pick out a bike of their own. Unfortunately, over a year into the pandemic, we were told if we ordered today, the bike would be delivered in 6 months.

Later that day, I visited the local used bike shop and was excitedly told that for \$400, I could have a refurbished 1997 Bianchi Timber Wolf, a bike which according to BikePedia.com, originally sold for \$300. Either this bike had a  [holographic Charizard](https://www.polygon.com/22356401/holographic-charizard-ebay-300k-sold-pokemon-cards) in its spokes, or demand for bikes is still very high.

Overall plans for my Arlington Bike Visualization project can be found in [this post]().


Part 1: Query the API
